### ISSUE TITLE
Aliasing on the bubblesub icon

### ISSUE THREAD

**Issue by Luni-4** [bubblesub/bubblesub#69]
On some small screens, the bubblesub icon presents an aliasing effect. 
It would be useful to provide icons at different dimensions, for example:

- 16x16
- 32x32
- 64x64
- 256x256

**Comment by rr-** [comment]
Please check my changes on the `icon-mipmaps` branch and let me know if they improve the issue for you

**Comment by Luni-4** [comment]
Unfortunately your changes don't fix the issue. But if I run the following code, the problem is fixed. I've also tried to use the 32 and 16 versions of the icon, but they are too blurred.

```
        icon = QtGui.QIcon(str(ROOT_DIR / "bubblesub-icon-64.png"))
        self.setWindowIcon(icon)
```

**Comment by rr-** [comment]
I updated the branch with your suggestion, let me know if it fixes the issue for you now. (Then again it appears `.addFile` does nothing in our case so we don't need that many copies)

**Comment by Luni-4** [comment]
Unfortunately it doesn't work again. If I comment the `mipmap` code, it works though.

**Comment by rr-** [comment]
This is stupid… OK I'll remove mipmaps but I'll keep the files

**Comment by Luni-4** [comment]
Let me update to `PyQt5 5.14.1` first, perhaps it is a dependency problem.

**Comment by Luni-4** [comment]
After having updated `PyQt` to the last version, the problem remains

**Comment by rr-** [comment]
See the newest branch

**Comment by Luni-4** [comment]
It works now, thank you!

**Comment by rr-** [comment]
Reorganized the commits a bit and merged into master, LMK if I didn't break anything

**Comment by Luni-4** [comment]
It works perfectly now, thanks a lot! :)
